// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Cmd.proto

package cn.monkey.proto;

public final class Command {
  private Command() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResultMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.monkey.proto.ResultMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    java.lang.String getMsg();
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code cn.monkey.proto.ResultMessage}
   */
  public static final class ResultMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.monkey.proto.ResultMessage)
      ResultMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ResultMessage.newBuilder() to construct.
    private ResultMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResultMessage() {
      msg_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ResultMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResultMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              msg_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.monkey.proto.Command.internal_static_cn_monkey_proto_ResultMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.monkey.proto.Command.internal_static_cn_monkey_proto_ResultMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.monkey.proto.Command.ResultMessage.class, cn.monkey.proto.Command.ResultMessage.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object msg_;
    /**
     * <code>string msg = 2;</code>
     * @return The msg.
     */
    @java.lang.Override
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        msg_ = s;
        return s;
      }
    }
    /**
     * <code>string msg = 2;</code>
     * @return The bytes for msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, msg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (!getMsgBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, msg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.monkey.proto.Command.ResultMessage)) {
        return super.equals(obj);
      }
      cn.monkey.proto.Command.ResultMessage other = (cn.monkey.proto.Command.ResultMessage) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMsg()
          .equals(other.getMsg())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.monkey.proto.Command.ResultMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.monkey.proto.Command.ResultMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.monkey.proto.Command.ResultMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.monkey.proto.Command.ResultMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.monkey.proto.Command.ResultMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.monkey.proto.Command.ResultMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.monkey.proto.Command.ResultMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.monkey.proto.Command.ResultMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.monkey.proto.Command.ResultMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.monkey.proto.Command.ResultMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.monkey.proto.Command.ResultMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.monkey.proto.Command.ResultMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.monkey.proto.Command.ResultMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.monkey.proto.ResultMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.monkey.proto.ResultMessage)
        cn.monkey.proto.Command.ResultMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.monkey.proto.Command.internal_static_cn_monkey_proto_ResultMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.monkey.proto.Command.internal_static_cn_monkey_proto_ResultMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.monkey.proto.Command.ResultMessage.class, cn.monkey.proto.Command.ResultMessage.Builder.class);
      }

      // Construct using cn.monkey.proto.Command.ResultMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        msg_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.monkey.proto.Command.internal_static_cn_monkey_proto_ResultMessage_descriptor;
      }

      @java.lang.Override
      public cn.monkey.proto.Command.ResultMessage getDefaultInstanceForType() {
        return cn.monkey.proto.Command.ResultMessage.getDefaultInstance();
      }

      @java.lang.Override
      public cn.monkey.proto.Command.ResultMessage build() {
        cn.monkey.proto.Command.ResultMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.monkey.proto.Command.ResultMessage buildPartial() {
        cn.monkey.proto.Command.ResultMessage result = new cn.monkey.proto.Command.ResultMessage(this);
        result.code_ = code_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.monkey.proto.Command.ResultMessage) {
          return mergeFrom((cn.monkey.proto.Command.ResultMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.monkey.proto.Command.ResultMessage other) {
        if (other == cn.monkey.proto.Command.ResultMessage.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMsg().isEmpty()) {
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.monkey.proto.Command.ResultMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.monkey.proto.Command.ResultMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object msg_ = "";
      /**
       * <code>string msg = 2;</code>
       * @return The msg.
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @return The bytes for msg.
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>string msg = 2;</code>
       * @param value The bytes for msg to set.
       * @return This builder for chaining.
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        msg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.monkey.proto.ResultMessage)
    }

    // @@protoc_insertion_point(class_scope:cn.monkey.proto.ResultMessage)
    private static final cn.monkey.proto.Command.ResultMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.monkey.proto.Command.ResultMessage();
    }

    public static cn.monkey.proto.Command.ResultMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResultMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResultMessage>() {
      @java.lang.Override
      public ResultMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ResultMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResultMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResultMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.monkey.proto.Command.ResultMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PackageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.monkey.proto.Package)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
     * @return Whether the resultMsg field is set.
     */
    boolean hasResultMsg();
    /**
     * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
     * @return The resultMsg.
     */
    cn.monkey.proto.Command.ResultMessage getResultMsg();
    /**
     * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
     */
    cn.monkey.proto.Command.ResultMessageOrBuilder getResultMsgOrBuilder();

    /**
     * <code>string groupId = 2;</code>
     * @return The groupId.
     */
    java.lang.String getGroupId();
    /**
     * <code>string groupId = 2;</code>
     * @return The bytes for groupId.
     */
    com.google.protobuf.ByteString
        getGroupIdBytes();

    /**
     * <code>int32 cmdType = 3;</code>
     * @return The cmdType.
     */
    int getCmdType();

    /**
     * <code>bytes content = 4;</code>
     * @return The content.
     */
    com.google.protobuf.ByteString getContent();
  }
  /**
   * Protobuf type {@code cn.monkey.proto.Package}
   */
  public static final class Package extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.monkey.proto.Package)
      PackageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Package.newBuilder() to construct.
    private Package(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Package() {
      groupId_ = "";
      content_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Package();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Package(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              cn.monkey.proto.Command.ResultMessage.Builder subBuilder = null;
              if (resultMsg_ != null) {
                subBuilder = resultMsg_.toBuilder();
              }
              resultMsg_ = input.readMessage(cn.monkey.proto.Command.ResultMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(resultMsg_);
                resultMsg_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              groupId_ = s;
              break;
            }
            case 24: {

              cmdType_ = input.readInt32();
              break;
            }
            case 34: {

              content_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.monkey.proto.Command.internal_static_cn_monkey_proto_Package_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.monkey.proto.Command.internal_static_cn_monkey_proto_Package_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.monkey.proto.Command.Package.class, cn.monkey.proto.Command.Package.Builder.class);
    }

    public static final int RESULTMSG_FIELD_NUMBER = 1;
    private cn.monkey.proto.Command.ResultMessage resultMsg_;
    /**
     * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
     * @return Whether the resultMsg field is set.
     */
    @java.lang.Override
    public boolean hasResultMsg() {
      return resultMsg_ != null;
    }
    /**
     * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
     * @return The resultMsg.
     */
    @java.lang.Override
    public cn.monkey.proto.Command.ResultMessage getResultMsg() {
      return resultMsg_ == null ? cn.monkey.proto.Command.ResultMessage.getDefaultInstance() : resultMsg_;
    }
    /**
     * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
     */
    @java.lang.Override
    public cn.monkey.proto.Command.ResultMessageOrBuilder getResultMsgOrBuilder() {
      return getResultMsg();
    }

    public static final int GROUPID_FIELD_NUMBER = 2;
    private volatile java.lang.Object groupId_;
    /**
     * <code>string groupId = 2;</code>
     * @return The groupId.
     */
    @java.lang.Override
    public java.lang.String getGroupId() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        groupId_ = s;
        return s;
      }
    }
    /**
     * <code>string groupId = 2;</code>
     * @return The bytes for groupId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGroupIdBytes() {
      java.lang.Object ref = groupId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        groupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMDTYPE_FIELD_NUMBER = 3;
    private int cmdType_;
    /**
     * <code>int32 cmdType = 3;</code>
     * @return The cmdType.
     */
    @java.lang.Override
    public int getCmdType() {
      return cmdType_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString content_;
    /**
     * <code>bytes content = 4;</code>
     * @return The content.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getContent() {
      return content_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (resultMsg_ != null) {
        output.writeMessage(1, getResultMsg());
      }
      if (!getGroupIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, groupId_);
      }
      if (cmdType_ != 0) {
        output.writeInt32(3, cmdType_);
      }
      if (!content_.isEmpty()) {
        output.writeBytes(4, content_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (resultMsg_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getResultMsg());
      }
      if (!getGroupIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, groupId_);
      }
      if (cmdType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, cmdType_);
      }
      if (!content_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.monkey.proto.Command.Package)) {
        return super.equals(obj);
      }
      cn.monkey.proto.Command.Package other = (cn.monkey.proto.Command.Package) obj;

      if (hasResultMsg() != other.hasResultMsg()) return false;
      if (hasResultMsg()) {
        if (!getResultMsg()
            .equals(other.getResultMsg())) return false;
      }
      if (!getGroupId()
          .equals(other.getGroupId())) return false;
      if (getCmdType()
          != other.getCmdType()) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasResultMsg()) {
        hash = (37 * hash) + RESULTMSG_FIELD_NUMBER;
        hash = (53 * hash) + getResultMsg().hashCode();
      }
      hash = (37 * hash) + GROUPID_FIELD_NUMBER;
      hash = (53 * hash) + getGroupId().hashCode();
      hash = (37 * hash) + CMDTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getCmdType();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.monkey.proto.Command.Package parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.monkey.proto.Command.Package parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.monkey.proto.Command.Package parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.monkey.proto.Command.Package parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.monkey.proto.Command.Package parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.monkey.proto.Command.Package parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.monkey.proto.Command.Package parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.monkey.proto.Command.Package parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.monkey.proto.Command.Package parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.monkey.proto.Command.Package parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.monkey.proto.Command.Package parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.monkey.proto.Command.Package parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.monkey.proto.Command.Package prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.monkey.proto.Package}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.monkey.proto.Package)
        cn.monkey.proto.Command.PackageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.monkey.proto.Command.internal_static_cn_monkey_proto_Package_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.monkey.proto.Command.internal_static_cn_monkey_proto_Package_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.monkey.proto.Command.Package.class, cn.monkey.proto.Command.Package.Builder.class);
      }

      // Construct using cn.monkey.proto.Command.Package.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (resultMsgBuilder_ == null) {
          resultMsg_ = null;
        } else {
          resultMsg_ = null;
          resultMsgBuilder_ = null;
        }
        groupId_ = "";

        cmdType_ = 0;

        content_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.monkey.proto.Command.internal_static_cn_monkey_proto_Package_descriptor;
      }

      @java.lang.Override
      public cn.monkey.proto.Command.Package getDefaultInstanceForType() {
        return cn.monkey.proto.Command.Package.getDefaultInstance();
      }

      @java.lang.Override
      public cn.monkey.proto.Command.Package build() {
        cn.monkey.proto.Command.Package result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.monkey.proto.Command.Package buildPartial() {
        cn.monkey.proto.Command.Package result = new cn.monkey.proto.Command.Package(this);
        if (resultMsgBuilder_ == null) {
          result.resultMsg_ = resultMsg_;
        } else {
          result.resultMsg_ = resultMsgBuilder_.build();
        }
        result.groupId_ = groupId_;
        result.cmdType_ = cmdType_;
        result.content_ = content_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.monkey.proto.Command.Package) {
          return mergeFrom((cn.monkey.proto.Command.Package)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.monkey.proto.Command.Package other) {
        if (other == cn.monkey.proto.Command.Package.getDefaultInstance()) return this;
        if (other.hasResultMsg()) {
          mergeResultMsg(other.getResultMsg());
        }
        if (!other.getGroupId().isEmpty()) {
          groupId_ = other.groupId_;
          onChanged();
        }
        if (other.getCmdType() != 0) {
          setCmdType(other.getCmdType());
        }
        if (other.getContent() != com.google.protobuf.ByteString.EMPTY) {
          setContent(other.getContent());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.monkey.proto.Command.Package parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.monkey.proto.Command.Package) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private cn.monkey.proto.Command.ResultMessage resultMsg_;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.monkey.proto.Command.ResultMessage, cn.monkey.proto.Command.ResultMessage.Builder, cn.monkey.proto.Command.ResultMessageOrBuilder> resultMsgBuilder_;
      /**
       * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
       * @return Whether the resultMsg field is set.
       */
      public boolean hasResultMsg() {
        return resultMsgBuilder_ != null || resultMsg_ != null;
      }
      /**
       * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
       * @return The resultMsg.
       */
      public cn.monkey.proto.Command.ResultMessage getResultMsg() {
        if (resultMsgBuilder_ == null) {
          return resultMsg_ == null ? cn.monkey.proto.Command.ResultMessage.getDefaultInstance() : resultMsg_;
        } else {
          return resultMsgBuilder_.getMessage();
        }
      }
      /**
       * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
       */
      public Builder setResultMsg(cn.monkey.proto.Command.ResultMessage value) {
        if (resultMsgBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resultMsg_ = value;
          onChanged();
        } else {
          resultMsgBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
       */
      public Builder setResultMsg(
          cn.monkey.proto.Command.ResultMessage.Builder builderForValue) {
        if (resultMsgBuilder_ == null) {
          resultMsg_ = builderForValue.build();
          onChanged();
        } else {
          resultMsgBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
       */
      public Builder mergeResultMsg(cn.monkey.proto.Command.ResultMessage value) {
        if (resultMsgBuilder_ == null) {
          if (resultMsg_ != null) {
            resultMsg_ =
              cn.monkey.proto.Command.ResultMessage.newBuilder(resultMsg_).mergeFrom(value).buildPartial();
          } else {
            resultMsg_ = value;
          }
          onChanged();
        } else {
          resultMsgBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
       */
      public Builder clearResultMsg() {
        if (resultMsgBuilder_ == null) {
          resultMsg_ = null;
          onChanged();
        } else {
          resultMsg_ = null;
          resultMsgBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
       */
      public cn.monkey.proto.Command.ResultMessage.Builder getResultMsgBuilder() {
        
        onChanged();
        return getResultMsgFieldBuilder().getBuilder();
      }
      /**
       * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
       */
      public cn.monkey.proto.Command.ResultMessageOrBuilder getResultMsgOrBuilder() {
        if (resultMsgBuilder_ != null) {
          return resultMsgBuilder_.getMessageOrBuilder();
        } else {
          return resultMsg_ == null ?
              cn.monkey.proto.Command.ResultMessage.getDefaultInstance() : resultMsg_;
        }
      }
      /**
       * <code>.cn.monkey.proto.ResultMessage resultMsg = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.monkey.proto.Command.ResultMessage, cn.monkey.proto.Command.ResultMessage.Builder, cn.monkey.proto.Command.ResultMessageOrBuilder> 
          getResultMsgFieldBuilder() {
        if (resultMsgBuilder_ == null) {
          resultMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.monkey.proto.Command.ResultMessage, cn.monkey.proto.Command.ResultMessage.Builder, cn.monkey.proto.Command.ResultMessageOrBuilder>(
                  getResultMsg(),
                  getParentForChildren(),
                  isClean());
          resultMsg_ = null;
        }
        return resultMsgBuilder_;
      }

      private java.lang.Object groupId_ = "";
      /**
       * <code>string groupId = 2;</code>
       * @return The groupId.
       */
      public java.lang.String getGroupId() {
        java.lang.Object ref = groupId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          groupId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string groupId = 2;</code>
       * @return The bytes for groupId.
       */
      public com.google.protobuf.ByteString
          getGroupIdBytes() {
        java.lang.Object ref = groupId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          groupId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string groupId = 2;</code>
       * @param value The groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string groupId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGroupId() {
        
        groupId_ = getDefaultInstance().getGroupId();
        onChanged();
        return this;
      }
      /**
       * <code>string groupId = 2;</code>
       * @param value The bytes for groupId to set.
       * @return This builder for chaining.
       */
      public Builder setGroupIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        groupId_ = value;
        onChanged();
        return this;
      }

      private int cmdType_ ;
      /**
       * <code>int32 cmdType = 3;</code>
       * @return The cmdType.
       */
      @java.lang.Override
      public int getCmdType() {
        return cmdType_;
      }
      /**
       * <code>int32 cmdType = 3;</code>
       * @param value The cmdType to set.
       * @return This builder for chaining.
       */
      public Builder setCmdType(int value) {
        
        cmdType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 cmdType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmdType() {
        
        cmdType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString content_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes content = 4;</code>
       * @return The content.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getContent() {
        return content_;
      }
      /**
       * <code>bytes content = 4;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes content = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.monkey.proto.Package)
    }

    // @@protoc_insertion_point(class_scope:cn.monkey.proto.Package)
    private static final cn.monkey.proto.Command.Package DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.monkey.proto.Command.Package();
    }

    public static cn.monkey.proto.Command.Package getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Package>
        PARSER = new com.google.protobuf.AbstractParser<Package>() {
      @java.lang.Override
      public Package parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Package(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Package> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Package> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.monkey.proto.Command.Package getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PackageGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.monkey.proto.PackageGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
     */
    java.util.List<cn.monkey.proto.Command.Package> 
        getPackagesList();
    /**
     * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
     */
    cn.monkey.proto.Command.Package getPackages(int index);
    /**
     * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
     */
    int getPackagesCount();
    /**
     * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
     */
    java.util.List<? extends cn.monkey.proto.Command.PackageOrBuilder> 
        getPackagesOrBuilderList();
    /**
     * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
     */
    cn.monkey.proto.Command.PackageOrBuilder getPackagesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code cn.monkey.proto.PackageGroup}
   */
  public static final class PackageGroup extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.monkey.proto.PackageGroup)
      PackageGroupOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PackageGroup.newBuilder() to construct.
    private PackageGroup(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PackageGroup() {
      packages_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PackageGroup();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PackageGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                packages_ = new java.util.ArrayList<cn.monkey.proto.Command.Package>();
                mutable_bitField0_ |= 0x00000001;
              }
              packages_.add(
                  input.readMessage(cn.monkey.proto.Command.Package.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          packages_ = java.util.Collections.unmodifiableList(packages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.monkey.proto.Command.internal_static_cn_monkey_proto_PackageGroup_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.monkey.proto.Command.internal_static_cn_monkey_proto_PackageGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.monkey.proto.Command.PackageGroup.class, cn.monkey.proto.Command.PackageGroup.Builder.class);
    }

    public static final int PACKAGES_FIELD_NUMBER = 1;
    private java.util.List<cn.monkey.proto.Command.Package> packages_;
    /**
     * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<cn.monkey.proto.Command.Package> getPackagesList() {
      return packages_;
    }
    /**
     * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends cn.monkey.proto.Command.PackageOrBuilder> 
        getPackagesOrBuilderList() {
      return packages_;
    }
    /**
     * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
     */
    @java.lang.Override
    public int getPackagesCount() {
      return packages_.size();
    }
    /**
     * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
     */
    @java.lang.Override
    public cn.monkey.proto.Command.Package getPackages(int index) {
      return packages_.get(index);
    }
    /**
     * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
     */
    @java.lang.Override
    public cn.monkey.proto.Command.PackageOrBuilder getPackagesOrBuilder(
        int index) {
      return packages_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < packages_.size(); i++) {
        output.writeMessage(1, packages_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < packages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, packages_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.monkey.proto.Command.PackageGroup)) {
        return super.equals(obj);
      }
      cn.monkey.proto.Command.PackageGroup other = (cn.monkey.proto.Command.PackageGroup) obj;

      if (!getPackagesList()
          .equals(other.getPackagesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPackagesCount() > 0) {
        hash = (37 * hash) + PACKAGES_FIELD_NUMBER;
        hash = (53 * hash) + getPackagesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.monkey.proto.Command.PackageGroup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.monkey.proto.Command.PackageGroup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.monkey.proto.Command.PackageGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.monkey.proto.Command.PackageGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.monkey.proto.Command.PackageGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.monkey.proto.Command.PackageGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.monkey.proto.Command.PackageGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.monkey.proto.Command.PackageGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.monkey.proto.Command.PackageGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.monkey.proto.Command.PackageGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.monkey.proto.Command.PackageGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.monkey.proto.Command.PackageGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.monkey.proto.Command.PackageGroup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.monkey.proto.PackageGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.monkey.proto.PackageGroup)
        cn.monkey.proto.Command.PackageGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.monkey.proto.Command.internal_static_cn_monkey_proto_PackageGroup_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.monkey.proto.Command.internal_static_cn_monkey_proto_PackageGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.monkey.proto.Command.PackageGroup.class, cn.monkey.proto.Command.PackageGroup.Builder.class);
      }

      // Construct using cn.monkey.proto.Command.PackageGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPackagesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (packagesBuilder_ == null) {
          packages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          packagesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.monkey.proto.Command.internal_static_cn_monkey_proto_PackageGroup_descriptor;
      }

      @java.lang.Override
      public cn.monkey.proto.Command.PackageGroup getDefaultInstanceForType() {
        return cn.monkey.proto.Command.PackageGroup.getDefaultInstance();
      }

      @java.lang.Override
      public cn.monkey.proto.Command.PackageGroup build() {
        cn.monkey.proto.Command.PackageGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cn.monkey.proto.Command.PackageGroup buildPartial() {
        cn.monkey.proto.Command.PackageGroup result = new cn.monkey.proto.Command.PackageGroup(this);
        int from_bitField0_ = bitField0_;
        if (packagesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            packages_ = java.util.Collections.unmodifiableList(packages_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.packages_ = packages_;
        } else {
          result.packages_ = packagesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.monkey.proto.Command.PackageGroup) {
          return mergeFrom((cn.monkey.proto.Command.PackageGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.monkey.proto.Command.PackageGroup other) {
        if (other == cn.monkey.proto.Command.PackageGroup.getDefaultInstance()) return this;
        if (packagesBuilder_ == null) {
          if (!other.packages_.isEmpty()) {
            if (packages_.isEmpty()) {
              packages_ = other.packages_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePackagesIsMutable();
              packages_.addAll(other.packages_);
            }
            onChanged();
          }
        } else {
          if (!other.packages_.isEmpty()) {
            if (packagesBuilder_.isEmpty()) {
              packagesBuilder_.dispose();
              packagesBuilder_ = null;
              packages_ = other.packages_;
              bitField0_ = (bitField0_ & ~0x00000001);
              packagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPackagesFieldBuilder() : null;
            } else {
              packagesBuilder_.addAllMessages(other.packages_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.monkey.proto.Command.PackageGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.monkey.proto.Command.PackageGroup) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<cn.monkey.proto.Command.Package> packages_ =
        java.util.Collections.emptyList();
      private void ensurePackagesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          packages_ = new java.util.ArrayList<cn.monkey.proto.Command.Package>(packages_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.monkey.proto.Command.Package, cn.monkey.proto.Command.Package.Builder, cn.monkey.proto.Command.PackageOrBuilder> packagesBuilder_;

      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public java.util.List<cn.monkey.proto.Command.Package> getPackagesList() {
        if (packagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(packages_);
        } else {
          return packagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public int getPackagesCount() {
        if (packagesBuilder_ == null) {
          return packages_.size();
        } else {
          return packagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public cn.monkey.proto.Command.Package getPackages(int index) {
        if (packagesBuilder_ == null) {
          return packages_.get(index);
        } else {
          return packagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public Builder setPackages(
          int index, cn.monkey.proto.Command.Package value) {
        if (packagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePackagesIsMutable();
          packages_.set(index, value);
          onChanged();
        } else {
          packagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public Builder setPackages(
          int index, cn.monkey.proto.Command.Package.Builder builderForValue) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          packages_.set(index, builderForValue.build());
          onChanged();
        } else {
          packagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public Builder addPackages(cn.monkey.proto.Command.Package value) {
        if (packagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePackagesIsMutable();
          packages_.add(value);
          onChanged();
        } else {
          packagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public Builder addPackages(
          int index, cn.monkey.proto.Command.Package value) {
        if (packagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePackagesIsMutable();
          packages_.add(index, value);
          onChanged();
        } else {
          packagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public Builder addPackages(
          cn.monkey.proto.Command.Package.Builder builderForValue) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          packages_.add(builderForValue.build());
          onChanged();
        } else {
          packagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public Builder addPackages(
          int index, cn.monkey.proto.Command.Package.Builder builderForValue) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          packages_.add(index, builderForValue.build());
          onChanged();
        } else {
          packagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public Builder addAllPackages(
          java.lang.Iterable<? extends cn.monkey.proto.Command.Package> values) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, packages_);
          onChanged();
        } else {
          packagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public Builder clearPackages() {
        if (packagesBuilder_ == null) {
          packages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          packagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public Builder removePackages(int index) {
        if (packagesBuilder_ == null) {
          ensurePackagesIsMutable();
          packages_.remove(index);
          onChanged();
        } else {
          packagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public cn.monkey.proto.Command.Package.Builder getPackagesBuilder(
          int index) {
        return getPackagesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public cn.monkey.proto.Command.PackageOrBuilder getPackagesOrBuilder(
          int index) {
        if (packagesBuilder_ == null) {
          return packages_.get(index);  } else {
          return packagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public java.util.List<? extends cn.monkey.proto.Command.PackageOrBuilder> 
           getPackagesOrBuilderList() {
        if (packagesBuilder_ != null) {
          return packagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(packages_);
        }
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public cn.monkey.proto.Command.Package.Builder addPackagesBuilder() {
        return getPackagesFieldBuilder().addBuilder(
            cn.monkey.proto.Command.Package.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public cn.monkey.proto.Command.Package.Builder addPackagesBuilder(
          int index) {
        return getPackagesFieldBuilder().addBuilder(
            index, cn.monkey.proto.Command.Package.getDefaultInstance());
      }
      /**
       * <code>repeated .cn.monkey.proto.Package packages = 1;</code>
       */
      public java.util.List<cn.monkey.proto.Command.Package.Builder> 
           getPackagesBuilderList() {
        return getPackagesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          cn.monkey.proto.Command.Package, cn.monkey.proto.Command.Package.Builder, cn.monkey.proto.Command.PackageOrBuilder> 
          getPackagesFieldBuilder() {
        if (packagesBuilder_ == null) {
          packagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              cn.monkey.proto.Command.Package, cn.monkey.proto.Command.Package.Builder, cn.monkey.proto.Command.PackageOrBuilder>(
                  packages_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          packages_ = null;
        }
        return packagesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.monkey.proto.PackageGroup)
    }

    // @@protoc_insertion_point(class_scope:cn.monkey.proto.PackageGroup)
    private static final cn.monkey.proto.Command.PackageGroup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.monkey.proto.Command.PackageGroup();
    }

    public static cn.monkey.proto.Command.PackageGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PackageGroup>
        PARSER = new com.google.protobuf.AbstractParser<PackageGroup>() {
      @java.lang.Override
      public PackageGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PackageGroup(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PackageGroup> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PackageGroup> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cn.monkey.proto.Command.PackageGroup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_monkey_proto_ResultMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_monkey_proto_ResultMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_monkey_proto_Package_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_monkey_proto_Package_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_monkey_proto_PackageGroup_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_monkey_proto_PackageGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tCmd.proto\022\017cn.monkey.proto\"*\n\rResultMe" +
      "ssage\022\014\n\004code\030\001 \001(\005\022\013\n\003msg\030\002 \001(\t\"o\n\007Pack" +
      "age\0221\n\tresultMsg\030\001 \001(\0132\036.cn.monkey.proto" +
      ".ResultMessage\022\017\n\007groupId\030\002 \001(\t\022\017\n\007cmdTy" +
      "pe\030\003 \001(\005\022\017\n\007content\030\004 \001(\014\":\n\014PackageGrou" +
      "p\022*\n\010packages\030\001 \003(\0132\030.cn.monkey.proto.Pa" +
      "ckageB\013B\007CommandH\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_cn_monkey_proto_ResultMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_monkey_proto_ResultMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_monkey_proto_ResultMessage_descriptor,
        new java.lang.String[] { "Code", "Msg", });
    internal_static_cn_monkey_proto_Package_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_monkey_proto_Package_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_monkey_proto_Package_descriptor,
        new java.lang.String[] { "ResultMsg", "GroupId", "CmdType", "Content", });
    internal_static_cn_monkey_proto_PackageGroup_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_monkey_proto_PackageGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_monkey_proto_PackageGroup_descriptor,
        new java.lang.String[] { "Packages", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
