resource:
  host: 192.168.126.163

spring:
  datasource:
    url: jdbc:mysql://${resource.host}/sys_order?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  redis:
    host: ${resource.host}
    port: 6379
server:
  port: 8081
